### ISSUE TITLE
Building in Linux support

### ISSUE THREAD

**Issue by abhishek-m-raj** [hahouari/inno_bundle#1]
Hey I am using GitHub cli to do this so how can this run on Linux since workflows run on Linux I found a docker for Linux can implement to run this thing in Linux also if you can you can switch to a project called flutter installer
That can package on every desktop and is fully made with flutter

**Comment by hahouari** [comment]
Hello there,

> how can this run on Linux...

Inno Setup is Windows only, so is this package (might change later).

> I found a docker for Linux...

If you are referring to Inno Setup docker image, I didn't try it yet, but would love to when I have some free time.

> you can switch to a project called flutter installer...

[This project?](https://github.com/YazeedAlKhalaf/Flutter_Installer) It is not built upon inno setup so I cannot see how it might be useful to switch to it (and appears to be unmaintained).

I have an idea, I didn't try it but worth a shot (if you can), use [Windows Github action](https://github.com/subosito/flutter-action) and employ a script to download [Inno Setup](https://jrsoftware.org/isdl.php) and install it , then you can run this package to build an installer for you.

**Comment by hahouari** [comment]
Hey, if you are still interested on how to run it as a GitHub action, checkout [this demo](https://github.com/hahouari/flutter_inno_workflows_demo) I have created to add GitHub automation support for `inno_bundle`.

**Comment by abhishek-m-raj** [comment]
I already impl it thanks for your response that was pretty nonsensical issue to make. I am terribly sorry.

**Comment by abhishek-m-raj** [comment]
`  build_windows:
    runs-on: windows-latest
    needs: check_version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          cache: true

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Set up Inno
        run: |
          Invoke-WebRequest -Uri 'https://jrsoftware.org/download.php/is.exe' -OutFile 'inno.exe'
          Start-Process -FilePath 'inno.exe' -ArgumentList '/VERYSILENT'
  
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Build Windows Installer
        run: dart run inno_bundle:build --release

      - name: Upload Windows Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-windows
          path: build/windows/x64/installer/Release/Sanji-x86_64-${{ needs.check_version.outputs.version }}-Installer.exe
          retention-days: 1`

This is way i did it could you plz mention this in the readme so people will not get lost or you can create a cmd that installs the innobundle silently if it is not installed also thanks for the package 💗

**Comment by hahouari** [comment]
No problem mate, in fact I planned to make such automation script, just didn't have motive to prioritize it.

Thank you for sharing your script here as well. Again, here is a more complete example that works without `needs: check_version`, I shared it on [this demo](https://github.com/hahouari/flutter_inno_workflows_demo).

```yaml
name: Main workflow
on:
  push:
    branches:
      - dev # <--- Put your branch of course
permissions:
  contents: write
jobs:
  windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Flutter
        uses: subosito/flutter-action@v2

      - name: Build Windows App
        run: |
          flutter config --enable-windows-desktop
          flutter build windows

      - name: Build iss script
        run: dart run inno_bundle:build --no-app --release --no-installer

      - name: Output config into github output
        id: envs
        # thanks to https://github.com/actions/runner/issues/2224#issuecomment-1289925992
        run: echo $(dart run inno_bundle:build --envs --no-hf) | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ./build/windows/x64/installer/Release/inno-script.iss

      - name: Release installer
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./build/windows/x64/installer/Release/${{ steps.envs.outputs.APP_NAME_CAMEL_CASE }}-x86_64-${{ steps.envs.outputs.APP_VERSION }}-Installer.exe
          name: "${{ steps.envs.outputs.APP_VERSION }}_${{ github.run_id }}"
          target_commitish: dev
          tag_name: "v${{ steps.envs.outputs.APP_VERSION }}_${{ github.run_id }}"
```
