### ISSUE TITLE
Bundled VCRUNTIME140 bug

### ISSUE THREAD

**Issue by kingdomseed** [hahouari/inno_bundle#13]
**Describe the bug**
The bundled and install DLL VCRUNTIME140.dll and VCRUNTIME140_1.dll cause the application to fail to load after install on Windows 10 and 11

**To Reproduce**
1. Launch the installer
2. Install the app
3. Run the app
4. App does not start: see error

**Expected behavior**
App should launch without this error

**Screenshots**

![Image](https://github.com/user-attachments/assets/294586f1-4009-49d8-80b5-5a62b599a535)

**Desktop (please complete the following information):**
Edition    Windows 10 Pro
Version    22H2
Installed on    ‎9/‎25/‎2021
OS build    19045.5555
Experience    Windows Feature Experience Pack 1000.19061.1000.0

Processor    AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
Installed RAM    32.0 GB
Device ID    EBAA5F2E-5DF6-4077-87EF-6AAE0451D036
Product ID    00330-53762-37759-AAOEM
System type    64-bit operating system, x64-based processor
Pen and touch    Pen support

**Additional context**
A work around: delete the installed VCRUNTIME140 and VCRUNTIME140_1 files from the application's install folder and ensure the latest VSRUNTIME is installed. Then the app loads fine.

**Comment by hahouari** [comment]
Hello @kingdomseed, thanks for reporting this,

It appears to be DLL compatibility conflict, a theory to this is that Windows version in this machine is very different than the one you used to create the installer, I didn't know such issues could arise. Indeed I shall implement a parameter in pubspec.yaml to control bundling these dlls to avoid such issues.

**Comment by hahouari** [comment]
Hello again,
Please update to new version `0.9.0`, and try adding this to your pubspec.yaml under inno_bundle section:
```yaml
inno_bundle:
  # ... other config
  vc_redist: false # to exclude vc redistributable DLLs from being bundled
  # or if you want your users to be redirected to download VC++ redistributables after installation
  vc_redist: "download"
```

I'm closing this, but if you encounter any issue with it, don't hesitate to reopen this.

Best of luck.
