### ISSUE TITLE
Windows is unable to find the .exe file when using a custom name for the app

### ISSUE THREAD

**Issue by maelchiotti** [hahouari/inno_bundle#2]
Hi,

Thanks for this amazing package, it makes it SO easier to publish an app on windows, and I love that you thought about GitHub actions.

I ran into an issue when using a custom name for my app. It appears that Windows is looking for a .exe file named <new_name>.exe. However the name of that exe name is <pubspec_name>.exe (where pubspec_name is the name of the project in the pubspec file, which is why there is no error when not using a custom name).

This can be fixed by editing the last line of the generated `nno_setup.iss` file :

```
[Run]
Filename: "{app}\<new_name>.exe"; Description: "{cm:LaunchProgram,{#StringChange('<new_name>', '&', '&&')}}"; Flags: nowait postinstall skipifsilent
```

to :

```
[Run]
Filename: "{app}\<pubspec_name>.exe"; Description: "{cm:LaunchProgram,{#StringChange('<pubspec_name>', '&', '&&')}}"; Flags: nowait postinstall skipifsilent
```

**Comment by hahouari** [comment]
Hi there,
I'm happy to know that you found out this package useful,

I understand the problem, is it possible to provide your pubspec.yaml here? at least a trimmed of version where it shows the important parts like name, and inno_bundle section, I will try to reproduce it if it's a bug.

If using GitHub actions, I would like to see your build.yaml or at least some parts of it, this could happen if enviroment variables are not set successfully on this step,
```yaml
      - name: Output config into github output
        id: envs
        # thanks to https://github.com/actions/runner/issues/2224#issuecomment-1289925992
        run: echo $(dart run inno_bundle:build --envs --no-hf) | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
```
But nothing to conclude yet, until I see more info :).

**Comment by maelchiotti** [comment]
Hi,

My pubspec, with the name under inno_bundle commented out because of the issue:
```yaml
name: cpm
description: Cinema Project Manager is a tool to efficiently manage the production of a cinema project.
repository: https://github.com/studiorvandco/cpm_app
documentation: https://github.com/studiorvandco/cpm_app/wiki

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  [...]

dev_dependencies:
  [...]

flutter:
  uses-material-design: true
  assets:
    - assets/logos/

inno_bundle:
  id: 74c43507-d381-5f15-b818-6d1a6731e317
  # name: Cinema Project Manager (CPM)
  publisher: Studio Rv & Co
  url: https://cpm.rvandco.fr
  support_url: https://rvandco.fr
  installer_icon: assets/icons/cpm.ico
  languages:
    - english
    - french
  ```

The part of my GitHub action that builds for Windows and uploads the result to the artifacts. The `needs.get_version.outputs.version` variable is the version of the app from the pubspec that I got in a previous step:

```yaml
build_windows:
    name: Windows
    environment: release
    runs-on: windows-latest
    needs: [ get_version ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build app
        run: flutter build windows --release
      - name: Build InnoSetup script
        run: dart run inno_bundle:build --no-app --release --no-installer
      - name: Build EXE
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build/windows/x64/installer/Release/inno-script.iss
      - name: Output InnoSetup env variables
        id: envs
        run: echo $(dart run inno_bundle:build --envs --no-hf) | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Rename EXE
        run: Rename-Item -Path "build/windows/x64/installer/Release/${{ steps.envs.outputs.APP_NAME_CAMEL_CASE }}-x86_64-${{ steps.envs.outputs.APP_VERSION }}-Installer.exe" -NewName "CPM_${{ needs.get_version.outputs.version }}.exe"
      - name: Archive EXE
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/windows/x64/installer/Release/CPM_${{ needs.get_version.outputs.version }}.exe
```

I do have this issue just locally, without using GitHub actions, just by using any name under inno_bundle that is not the name of the flutter project.
